name: Build SOFA macOS2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone SOFA
        run: |
          git clone https://github.com/Starlink/sofa.git --single-branch --branch=vendor IAU_SOFA

      - name: Build SOFA
        run: |
          cd IAU_SOFA 
          mkdir Release 
          cd src 
          make 
          mv libsofa_c.a ../Release/
      
      - name: Verify library
        run: ls -l ${{ github.workspace }}/SGP4/Release/libsgp4

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: sofa-macos
          path: ${{ github.workspace }}/IAU_SOFA/libsofa_c.a

