name: Build VieSched++ macOS3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Cache Qt
        uses: actions/cache@v4
        with:
          path: |
            /opt/homebrew/Cellar/qt
            /opt/homebrew/opt/qt
          key: ${{ runner.os }}-qt
          
      - name: Install Qt
        run: brew install qt
        
      - name: Add Qt to PATH
        run: echo "$(brew --prefix qt)/bin" >> $GITHUB_PATH

      - name: Inspect Qt installation
        run: |
          brew --prefix qt
          ls -R $(brew --prefix qt)

      - name: Install Boost
        run: brew install boost
        
      - name: Install tools
        run: |
          brew install cmake git

      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt)

      - name: Show repository structure
        run: |
          pwd
          ls -R
          
      - name: Build project
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu)
          
      - name: Locate macdeployqt
        run: |
          echo "Looking for macdeployqt..."
          find $(brew --prefix qt) -name macdeployqt


      - name: Debug Qt tools
        run: |
          echo "PATH=$PATH"
          which macdeployqt || echo "macdeployqt not found"
          ls $(brew --prefix qt)/bin/macdeployqt


      - name: Deploy Qt libraries
        run: |
          cd build
          export DYLD_FRAMEWORK_PATH=/opt/homebrew/opt/qt/lib
          /opt/homebrew/opt/qt/bin/macdeployqt $GITHUB_WORKSPACE/build/VieSchedpp.app -verbose=1
          
      - name: Upload compiled app
        uses: actions/upload-artifact@v4
        with:
          name: VieSched-macos
          path: build/VieSchedpp.app

