name: Build and Upload Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release folder
        run: mkdir -p SGP4/Release

      - name: Copy files
        run: cp -r build/* SGP4/Release/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sgp4-release
          path: SGP4/Release
