name: Build SOFA macOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone SOFA library
        run: git clone https://github.com/Starlink/sofa.git

      - name: Build SOFA
        run: |
          cd sofa
          clang -c *.c
          ar rcs libsofa.a *.o

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libsofa-macos
          path: sofa/libsofa.a
