name: Build VieSched++ macOS2

on:
workflow_dispatch:

jobs:
build:
runs-on: macos-latest

```
steps:

- name: Checkout repository
  uses: actions/checkout@v4

- name: Install dependencies
  run: |
    brew update
    brew install cmake boost qt

# -------------------------
# Build SOFA
# -------------------------
- name: Build SOFA
  run: |
    git clone https://github.com/Starlink/sofa.git --single-branch --branch=vendor IAU_SOFA
    cd IAU_SOFA
    mkdir Release
    cd src
    make
    mv libsofa_c.a ../Release/

# -------------------------
# Build SGP4
# -------------------------
- name: Build SGP4
  run: |
    git clone https://github.com/dnwrnr/sgp4.git
    cd sgp4
    git checkout f5cb54b38
    mkdir Release
    cd Release
    cmake -DCMAKE_BUILD_TYPE=Release ..
    make

# -------------------------
# Build VieSched++
# -------------------------
- name: Build VieSched++
  run: |
    git clone https://github.com/TUW-VieVS/VieSchedpp.git
    cd VieSchedpp
    mkdir Release
    cd Release
    cmake -DCMAKE_BUILD_TYPE=Release ..
    make -j$(sysctl -n hw.ncpu)

# -------------------------
# Upload binary
# -------------------------
- name: Upload artifact
  uses: actions/upload-artifact@v4
  with:
    name: VieSchedpp-macos
    path: VieSchedpp/Release/VieSchedpp
```
