name: Build VieSched++ macOS3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        run: brew install qt

      - name: Install Boost
        run: brew install boost
        
      - name: Install tools
        run: |
          brew install cmake git

      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt)

      - name: Show repository structure
        run: |
          pwd
          ls -R
          
      - name: Build project
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu)

      - name: Deploy Qt libraries
        run: |
          cd build
          export PATH=$(brew --prefix qt)/bin:$PATH
          export DYLD_FRAMEWORK_PATH=$(brew --prefix qt)/lib
          macdeployqt VieSchedpp.app
          

      - name: Upload compiled app
        uses: actions/upload-artifact@v4
        with:
          name: VieSched-macos
          path: build/VieSchedpp.app

