name: Build SGP4 macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-sgp4:
    runs-on: macos-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install build tools
      - name: Install dependencies
        run: |
          brew install cmake git

      # 3. Clone and build SGP4
      - name: Build SGP4 library
        run: |
          rm -rf $GITHUB_WORKSPACE/SGP4
          git clone https://github.com/dnwrnr/sgp4.git $GITHUB_WORKSPACE/SGP4
          cd $GITHUB_WORKSPACE/SGP4
          git checkout f5cb54b38
          mkdir -p Release
          cd Release
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
          make sgp4

      # 4. Upload build outputs

      - name: Upload SGP4 libraries
        run: mkdir -p $GITHUB_WORKSPACE/SGP4/Release
      - uses: actions/upload-artifact@v4
        with:
          name: sgp4-libraries
          path: ${{ github.workspace }}/SGP4/Release/libsgp4


