name: Build VieSched++ macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows manual trigger

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # 1. Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2. Install Homebrew and Qt6
      - name: Install Qt
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install qt
        
      - name: Install Boost
        run: brew install boost
    
      # 3. Install CMake
      - name: Install build tools
        run: |
          brew install cmake git


      - name: Build SOFA 
        run: | 
          git clone https://github.com/Starlink/sofa.git --single-branch --branch=vendor IAU_SOFA 
          cd IAU_SOFA 
          mkdir Release 
          cd src 
          make 
          mv libsofa_c.a ../Release/


      - name: Build SGP4
        run: | 
          rm -rf SGP4
          git clone https://github.com/dnwrnr/sgp4.git SGP4
          cd sgp4
          git checkout f5cb54b38
          mkdir Release
          cd Release
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
          make sgp4

      # 4. Configure the project
      - name: Configure project
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt) \
            -DCMAKE_BUILD_TYPE=Release \
            -DIAU_SOFA_DIR=$GITHUB_WORKSPACE/IAU_SOFA/Release \
            -DSGP4_DIR=$GITHUB_WORKSPACE/sgp4/Release/libsgp4 \
            -DUSE_MINIZ=OFF \
            -DBOOST_ROOT=$(brew --prefix boost) \
            -DCMAKE_CXX_FLAGS="-I$GITHUB_WORKSPACE" \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DBoost_NO_SYSTEM_PATHS=ON \
            -DBoost_USE_STATIC_LIBS=OFF \
            -DBoost_USE_MULTITHREADED=ON \
            -DBoost_USE_STATIC_RUNTIME=OFF \
            -DBoost_COMPONENTS=system, thread, filesystem

      # 5. Build project
      - name: Build project
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu)

      # 6. Deploy Qt libraries
      - name: Deploy Qt
        run: |
          cd build
          /usr/local/opt/qt/bin/macdeployqt VieSched++.app

      # 7. Upload compiled app
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VieSched-macos
          path: build/VieSched++.app
